spring:
  application:
    name: spring-hhi

  datasource:
    url: jdbc:h2:mem:shipyard
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop     # 개발용: 실행마다 테이블 재생성
    show-sql: true              # 실행되는 SQL 로그
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true             # http://localhost:8080/h2-console